#
# pass for whitelisted (public) routes
# block for blacklisted routes
#
rules:
  pass:
    - api/v2/auth/public
    - api/v2/auth/identity
    - api/v2/trade/public
    - api/v2/trade/coinmarketcap
    - api/v2/trade/coingecko
    - api/v2/websocket/public
    - api/v2/applogic/public
    - api/v2/arke/public
    - api/v2/finex/public
  block:
    - api/v2/auth/management
    - api/v2/trade/management
    - api/v2/applogic/management
