name: Push to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: zeusdev27
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_REPO: opendax

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_HUB_REPO .
          docker push $DOCKER_HUB_REPO
